/*
 * generated by Xtext
 */
package org.xtext.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LanguageRuntimeModule extends org.xtext.language.AbstractLanguageRuntimeModule {

}
